#!/bin/sh

## started at runlevel 1 Single-user mode, 3 Full (text based) multi-user mode and 5 Full (GUI based) multi-user mode.
##/etc/rc1.d/S99nfs-srv-init  -> ../init.d/nfs-srv-init
##/etc/rc3.d/S99nfs-srv-init  -> ../init.d/nfs-srv-init
##/etc/rc5.d/S99nfs-srv-init  -> ../init.d/nfs-srv-init
/usr/bin/nfs-srv-setup
